/*********************************
 * 
 * 
 * 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
// Importation des classes nécessaires pour l'interface graphique
package chiffrement;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.*;

/**
 *
 * @author GLOBAL STORE
 */
public abstract class Chiffrements extends javax.swing.JFrame {
// Attribut pour définir le type de chiffrement
     protected TypeChiffrement typeChiffrement;
    /**
     * Creates new form Chiffrement_Cesar
     */
    public Chiffrements() {
        initComponents();
    }
// Méthodes permettant de récupérer différents composants de l'interface graphique
    public JButton getjBAnnuler() {
        return jBAnnuler;
    }

   protected JLabel getJLAcceuil() {
        return jLAcceuil;
    }

    protected void setJLAcceuilText(String text) {
        jLAcceuil.setText(text);
    } 

    public JButton getjBChiffre() {
        return jBChiffre;
    }

    public JButton getjBDechiffre() {
        return jBDechiffre;
    }

    public JButton getjBRetour() {
        return jBRetour;
    }

    public JButton getjBaide() {
        return jBaide;
    }

 
    public JTextField getjTClechiffrement() {
        return jTClechiffrement;
    }

    public JTextField getjTCledechiffrement() {
        return jTCledechiffrement;
    }

    public JTextField getjTmessageClaire() {
        return jTmessageClaire;
    }

    public JTextField getjTmessagechiffre() {
        return jTmessagechiffre;
    }

    public JTextField getjTmessagedechiffre() {
        return jTmessagedechiffre;
    }

    public void setjBAnnuler(JButton jBAnnuler) {
        this.jBAnnuler = jBAnnuler;
    }

    public void setjBChiffre(JButton jBChiffre) {
        this.jBChiffre = jBChiffre;
    }

    public void setjBDechiffre(JButton jBDechiffre) {
        this.jBDechiffre = jBDechiffre;
    }

    public void setjBRetour(JButton jBRetour) {
        this.jBRetour = jBRetour;
    }

    public void setjBaide(JButton jBaide) {
        this.jBaide = jBaide;
    }

    public void setjTClechiffrement(JTextField jTClechiffrement) {
        this.jTClechiffrement = jTClechiffrement;
    }

    public void setjTCledechiffrement(JTextField jTCledechiffrement) {
        this.jTCledechiffrement = jTCledechiffrement;
    }

    public void setjTmessageClaire(JTextField jTmessageClaire) {
        this.jTmessageClaire = jTmessageClaire;
    }

    public void setjTmessagechiffre(JTextField jTmessagechiffre) {
        this.jTmessagechiffre = jTmessagechiffre;
    }

    public void setjTmessagedechiffre(JTextField jTmessagedechiffre) {
        this.jTmessagedechiffre = jTmessagedechiffre;
    }
    

    // Méthodes abstraites pour chiffrer et déchiffrer un message
    public abstract String chiffrer ( String message, String cle);
    public abstract String dechiffrer(String messageChiffre, String cle);

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPchiffre = new javax.swing.JPanel();
        jLAcceuil = new javax.swing.JLabel();
        jBaide = new javax.swing.JButton();
        jLmessageClaire = new javax.swing.JLabel();
        jLClechiffrement = new javax.swing.JLabel();
        jLmessageChiffre = new javax.swing.JLabel();
        jLCledechiffrement = new javax.swing.JLabel();
        jLmessageDechiffre = new javax.swing.JLabel();
        jTmessageClaire = new javax.swing.JTextField();
        jTClechiffrement = new javax.swing.JTextField();
        jTmessagechiffre = new javax.swing.JTextField();
        jTCledechiffrement = new javax.swing.JTextField();
        jTmessagedechiffre = new javax.swing.JTextField();
        jBChiffre = new javax.swing.JButton();
        jBDechiffre = new javax.swing.JButton();
        jBAnnuler = new javax.swing.JButton();
        jBRetour = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPchiffre.setBackground(new java.awt.Color(153, 153, 255));
        jPchiffre.setForeground(new java.awt.Color(255, 255, 255));

        jLAcceuil.setBackground(new java.awt.Color(153, 153, 255));
        jLAcceuil.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLAcceuil.setForeground(new java.awt.Color(255, 255, 255));
        jLAcceuil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPchiffreLayout = new javax.swing.GroupLayout(jPchiffre);
        jPchiffre.setLayout(jPchiffreLayout);
        jPchiffreLayout.setHorizontalGroup(
            jPchiffreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLAcceuil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPchiffreLayout.setVerticalGroup(
            jPchiffreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLAcceuil, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
        );

        jBaide.setBackground(new java.awt.Color(0, 0, 255));
        jBaide.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jBaide.setForeground(new java.awt.Color(255, 255, 255));
        jBaide.setText("AIDE");

        jLmessageClaire.setBackground(new java.awt.Color(255, 255, 255));
        jLmessageClaire.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLmessageClaire.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLmessageClaire.setText("Message en Claire");

        jLClechiffrement.setBackground(new java.awt.Color(255, 255, 255));
        jLClechiffrement.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLClechiffrement.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLClechiffrement.setText("Clé de Chiffrement");

        jLmessageChiffre.setBackground(new java.awt.Color(255, 255, 255));
        jLmessageChiffre.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLmessageChiffre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLmessageChiffre.setText("Message Chiffré");

        jLCledechiffrement.setBackground(new java.awt.Color(255, 255, 255));
        jLCledechiffrement.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLCledechiffrement.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLCledechiffrement.setText("Clé de Déchiffrement");

        jLmessageDechiffre.setBackground(new java.awt.Color(255, 255, 255));
        jLmessageDechiffre.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLmessageDechiffre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLmessageDechiffre.setText("Message Déchiffré");

        jTmessageClaire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTmessageClaireActionPerformed(evt);
            }
        });

        jTClechiffrement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTClechiffrementActionPerformed(evt);
            }
        });

        jTCledechiffrement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTCledechiffrementActionPerformed(evt);
            }
        });

        jBChiffre.setBackground(new java.awt.Color(51, 51, 51));
        jBChiffre.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jBChiffre.setForeground(new java.awt.Color(255, 255, 255));
        jBChiffre.setText("Chiffré");
        jBChiffre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBChiffreActionPerformed(evt);
            }
        });

        jBDechiffre.setBackground(new java.awt.Color(51, 51, 51));
        jBDechiffre.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jBDechiffre.setForeground(new java.awt.Color(255, 255, 255));
        jBDechiffre.setText("Déchiffré");
        jBDechiffre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDechiffreActionPerformed(evt);
            }
        });

        jBAnnuler.setBackground(new java.awt.Color(51, 51, 51));
        jBAnnuler.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jBAnnuler.setForeground(new java.awt.Color(255, 255, 255));
        jBAnnuler.setText("Annuler");
        jBAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAnnulerActionPerformed(evt);
            }
        });

        jBRetour.setBackground(new java.awt.Color(51, 51, 51));
        jBRetour.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jBRetour.setForeground(new java.awt.Color(255, 255, 255));
        jBRetour.setText("Retour");
        jBRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRetourActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 0, 204));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("copy writting @ NGUEP MANYO JUNIOR GEROME");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPchiffre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLmessageClaire, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(62, 62, 62)
                        .addComponent(jTmessageClaire, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLClechiffrement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(62, 62, 62)
                        .addComponent(jTClechiffrement, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLmessageChiffre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(62, 62, 62)
                        .addComponent(jTmessagechiffre, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLCledechiffrement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(62, 62, 62)
                        .addComponent(jTCledechiffrement, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLmessageDechiffre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(62, 62, 62)
                        .addComponent(jTmessagedechiffre, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(69, 69, 69))
            .addGroup(layout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(jBaide, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBRetour)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBAnnuler))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBChiffre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBDechiffre)))))
                .addGap(108, 108, 108))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPchiffre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBaide)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLmessageClaire, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jTmessageClaire, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLClechiffrement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jTClechiffrement, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLmessageChiffre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jTmessagechiffre, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLCledechiffrement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jTCledechiffrement, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(jTmessagedechiffre, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jLmessageDechiffre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBChiffre)
                    .addComponent(jBDechiffre))
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBRetour)
                    .addComponent(jBAnnuler))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTClechiffrementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTClechiffrementActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTClechiffrementActionPerformed

    private void jTmessageClaireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTmessageClaireActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTmessageClaireActionPerformed

    private void jTCledechiffrementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTCledechiffrementActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTCledechiffrementActionPerformed
    // Action effectuée lors du clic sur le bouton de retour

    private void jBRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRetourActionPerformed
        // Crée une instance de la fenêtre Accueil et l'affiche

           Accueil A=new Accueil();
   A.setVisible(true);
   this.dispose();
           
       
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jBRetourActionPerformed
    // Action effectuée lors du clic sur le bouton d'annulation

    private void jBAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAnnulerActionPerformed
        // Réinitialise tous les champs de texte à des chaînes vides

    jTmessageClaire.setText("");
    jTClechiffrement.setText("");
    jTmessagechiffre.setText("");
    jTCledechiffrement.setText("");
    jTmessagedechiffre.setText(""); 

    }//GEN-LAST:event_jBAnnulerActionPerformed
    // Énumération définissant les différents types de chiffrements disponibles

    public enum TypeChiffrement {
    CESAR,
    HILL,
    VIGENERE
}
    
        // Action effectuée lors du clic sur le bouton de chiffrement

    private void jBChiffreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBChiffreActionPerformed
           // Récupère le message et la clé de chiffrement depuis les champs de texte

    String message = jTmessageClaire.getText();
    String cle = jTClechiffrement.getText();
      
    // Initialise une instance de Chiffrements

    Chiffrements chiffrement = null;
    
    // Sélectionne l'algorithme de chiffrement en fonction du typeChiffrement

    switch (typeChiffrement) {
        case CESAR:
            chiffrement = new Cesar();
            break;
        case HILL:
            chiffrement = new Hill();
            break;
        case VIGENERE:
            chiffrement = new Vigenere();
            break;
    }
        // Vérifie si un algorithme a été sélectionné, puis chiffre le message

    if (chiffrement != null) {
        String texteChiffre = chiffrement.chiffrer(message, cle);
        jTmessagechiffre.setText(texteChiffre);
    } else {
        // Gérer le cas où aucun algorithme n'est sélectionné
        System.out.println("Aucun algorithme de chiffrement sélectionné.");
    }
    }//GEN-LAST:event_jBChiffreActionPerformed

        // Action effectuée lors du clic sur le bouton de déchiffrement

    private void jBDechiffreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDechiffreActionPerformed
        // Récupère le message chiffré et la clé de déchiffrement depuis les champs de texte

     String message = jTmessagechiffre.getText();
    String cle = jTCledechiffrement.getText();
        // Initialise une instance de Chiffrements

    Chiffrements chiffrement = null;
        // Sélectionne l'algorithme de déchiffrement en fonction du typeChiffrement

    switch (typeChiffrement) {
        case CESAR:
            chiffrement = new Cesar();
            break;
        case HILL:
            chiffrement = new Hill();
            break;
        case VIGENERE:
            chiffrement = new Vigenere();
            break;
    }
        // Vérifie si un algorithme a été sélectionné, puis déchiffre le message

    if (chiffrement != null) {
        String texteDechiffre = chiffrement.dechiffrer(message, cle);
        jTmessagedechiffre.setText(texteDechiffre);
    } else {
        // Gérer le cas où aucun algorithme n'est sélectionné
        System.out.println("Aucun algorithme de déchiffrement sélectionné.");
    }
    }//GEN-LAST:event_jBDechiffreActionPerformed
   public abstract void initialiserInterfaceGraphique();
    // Méthode abstraite pour initialiser l'interface graphique (à implémenter dans les classes filles)

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAnnuler;
    private javax.swing.JButton jBChiffre;
    private javax.swing.JButton jBDechiffre;
    private javax.swing.JButton jBRetour;
    private javax.swing.JButton jBaide;
    private javax.swing.JLabel jLAcceuil;
    private javax.swing.JLabel jLClechiffrement;
    private javax.swing.JLabel jLCledechiffrement;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLmessageChiffre;
    private javax.swing.JLabel jLmessageClaire;
    private javax.swing.JLabel jLmessageDechiffre;
    private javax.swing.JPanel jPchiffre;
    private javax.swing.JTextField jTClechiffrement;
    private javax.swing.JTextField jTCledechiffrement;
    private javax.swing.JTextField jTmessageClaire;
    private javax.swing.JTextField jTmessagechiffre;
    private javax.swing.JTextField jTmessagedechiffre;
    // End of variables declaration//GEN-END:variables
}
